branches:
    only:
    - master

skip_tags: true

environment:
    nodejs_version: "8.11.3"

install:
    - npm i -g npm@6.3.0
    - npm install

build: off
deploy: off

test_script:
    - node --version
    - npm --version
    - npm run build

on_success:
    - cmd: npm run semantic-release
