environment:
    nodejs_version: "8.11.3"

install:
    - npm i -g npm@6.3.0
    - npm install

test_script:
    - node --version
    - npm --version

build_script:
    - cmd: npm run build

on_success:
    - cmd: npm run semantic-release
